Add files to VPN Folder
Otus-DevOps-2021-11/Maxx-4uTeP_infra pull request #5
Opened 2021-12-22 16:26 UTC by Maxx-4uTeP

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-12-22 16:27 UTC, Maxx-4uTeP commented
Нужно смерджить что то с чем то....

2021-12-24 08:05 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
ДЗ выполнено не корректно, нет коннекта в VPN 
Рекомендую свериться с методичкой, с разделом с описанием ридми
ДЗ возвращаю на доработку

2021-12-24 11:24 UTC, Maxx-4uTeP commented
и мерджа в итоге не видно тут
14:14
да и кода нету нифга)
14:14
на яндокс то
14:15
а как быть с текущими изменениями которые я не могу запушить
14:16
чот я ваще не отдупляю как гит работает.... все эти лекции прошли мимо
14:18
как я и писал в одной из домашек: тыкаемся как слепые котята наугад....

Vladimir D  14:19
Твой пуллреквест же смертен
14:19
Смержен
14:19
Т9 против меня

Макс М  14:19
))))
14:19
смерджен, а потом перенесены файлики в папку VPN
14:19
и теперь оно в непонятном статусе

Vladimir D  14:20
Потому что я я отклонил
14:20
Открой снова пр
14:20
И напиши что ты сделал
14:20
Потом поменжишь в мастер и все

2021-12-26 11:25 UTC, mrgreyves approved these changes
Описывать надо пуллреквесты все таки человеческим языком

2021-12-26 11:29 UTC, merged