terraform-2
Otus-DevOps-2021-11/Maxx-4uTeP_infra pull request #8
Opened 2022-01-12 11:56 UTC by Maxx-4uTeP

# Выполнено ДЗ №9

 - [v] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - всё по методичке.
 - звездочки сложно.
 - стр. 40 методички: _Проверьте правильность настроек инфраструктуры каждого
окружения. Для этого нужно запустить terraform apply в каждом
из них._   -- **запускается что то одно (или прод или стейдж). Второе говорит что имя уже занято...**

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [v] Выставил label с номером домашнего задания
 - [v] Выставил label с темой домашнего задания

2022-01-13 13:35 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно пофиксить пустые строки, посмотрите в тесте
Имя занято потому что конфиг применен, имя то можно и изменить =)

2022-01-13 13:42 UTC, mrgreyves requested changes
Снова тесты

2022-01-13 13:42 UTC, Maxx-4uTeP commented
пустые строки пофиксил (если вы про нехватку пустой строки в конце файлов)

2022-01-13 13:44 UTC, Maxx-4uTeP commented
Или про это речь?
```
     ×  Directory terraform/modules/vpc should exist
     expected Directory terraform/modules/vpc to exist
     ×  File terraform/storage-bucket.tf should exist
     expected File terraform/storage-bucket.tf to exist
     ×  File terraform/storage-bucket.tf content should match /\n\Z/
     expected nil to match /\n\Z/
```

2022-01-13 13:59 UTC, Maxx-4uTeP commented
тесты fixed. 
Но это странное делать пустые файлы/папки чтобы только прошли тесты...

2022-01-14 13:48 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2022-01-14 18:57 UTC, merged